jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v1
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: ${{ matrix.java-version }}
    - continue-on-error: true
      name: Maven Install
      run: mvn install -B -V -DskipTests -Dair.check.skip-all
    - continue-on-error: true
      name: Maven Tests
      run: mvn install -B -P ci
    strategy:
      fail-fast: false
      matrix:
        java-version:
        - 17
        - 21
        - 22-ea
name: ci
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
